name = "react-cloudflare"
type = "webpack"
account_id = "139be1921a6e796e176d5d88b6d0a8a6"
workers_dev = true
compatibility_date = "2020-01-01"

[site]
bucket = "./build"
entry-point = "worker-site"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"